name: .NET Console CI

on:
  push:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            9.0.x
            8.0.x
          cache: true

      - name: Build project
        run: dotnet build --no-restore --configuration Release ./Scr/test-ci/test-ci.csproj

      - name: Make test script executable
        run: chmod +x ./Scr/test.sh

      - name: Run test script
        run: ./scr/test.sh
