name: Manual API Task
on:
   repository_dispatch:
     inputs:
       environment:
         required: true
         options:
           - stage
           - production
jobs:
  incident-report:
    runs-on: ubuntu-latest
    steps:
      - name: incident-report
        run: echo "incident-report"
